config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :contacts, only: [:index, :show]
   get "/enquete" => "pages#enquete"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    include AlgoliaSearch
    
    algoliasearch per_environment: true, force_utf8_encoding: true do
        attributesToIndex ['company', 'zip', 'city', 'adr', 'chemise','manteau','couette', 'unordered(prestations)', 'region']
        attributesForFaceting ['company']
    end
    
    @@ALGOLIA_INDEX_NAME = "new_pressings"
    
    after_create :index_to_algolia
    after_destroy :remove_from_algolia
    
    def serialize_algolia
        {
            objectID: self.id,
            region:     self.region,
            lat:        self.lat,
            lng:	    self.lng,
            company:	self.company,
            adr:	    self.adr,
            zip:	    self.zip,
            city:	    self.city,
            couette:	self.couette,
            manteau:	self.manteau,
            chemise:	self.chemise,
            facebook:	self.facebook,
            website:	self.website,
            openinghours: self.openinghours,
            clients:	self.clients,
            phone:	    self.phone,
            phone2:	    self.phone2,
            prestations: self.prestations,
            reqgeocode:	self.reqgeocode,
            chmap:	    self.chmap
        }
    end
    
    def self.algolia_import
        self.all.each_slice(1000) do |batch|
        index = Algolia::Index.new(@@ALGOLIA_INDEX_NAME)
        #index.add_objects(Contact.all.map(&:serialize_algolia))
        index.add_objects(batch.map { |contact| contact.serialize_algolia })
        end
    end
    
    def index_to_algolia
        index = Algolia::Index.new(@@ALGOLIA_INDEX_NAME)
        index.save_object(self.serialize_algolia)
    end
    
    def remove_from_algolia
        index = Algolia::Index.new(@@ALGOLIA_INDEX_NAME)
        index.delete_object(self.id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    before_action :find_contact, only: [:show]
    def index
        @contacts = Contact.all
    end
    
    def show
    end
    
    
    private
    def find_contact
    @contact = Contact.find(params[:id])
    end
    
    def contact_params 
      params.require(:contact).permit( :region, :company, :adr, :zip, :city, 
      :couette, :manteau, :chemise, :facebook,:website, :openinghours, :clients, :phone,
      :phone2, :prestations)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/show.html.erb
<h1 class="text-center">
    <%=    @contact.company %>
</h1>
<h3 class="text-center">
   assumé par  <%=    @gossip.anonymous_author %>
</h3>
</br>

<p class="text-center">
    
    <%= link_to "Retour à l'accueil", root_path, class:"btn btn-success" %> 
    
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    
    
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/instantsearch.js@2.3.3/dist/instantsearch-theme-algolia.min.css">

  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>

  </body>
</html>

app/views/pages/enquete.html.erb
<div class="typeform-widget" data-url="https://hacktivistes.typeform.com/to/R6isYG" style="width: 100%; height: 700px;" > </div> <script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script> <div style="font-family: Sans-Serif;font-size: 12px;color: #999;opacity: 0.5; padding-top: 5px;" > powered by <a href="https://www.typeform.com//?utm_campaign=R6isYG&amp;utm_source=typeform.com-11473698-Pro&amp;utm_medium=typeform&amp;utm_content=typeform-embedded-poweredbytypeform&amp;utm_term=FR" style="color: #999" target="_blank">Typeform</a> </div>

app/views/pages/home.html.erb
<div class='search-box-wrapper'>
  <div class='search-box'>
    <div id='inputfield'>
      <i class='fa fa-search icon-search'></i>
      <input autocomplete='off' autocorrect='off' placeholder='Cherche pas, trouve !' spellcheck='false' type='text'>
    </div>
  </div>
</div>

<section class='panel'>
  <div class='panel-body'>
    <div class='text-right p-3' id='stats'></div>
    <div id='facets'></div>
    <div id='hits'></div>
  </div>
</section>

<main>
    <div id="hits"></div>
    <div id="pagination"></div>
</main>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">

  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>




<%= link_to "Enquête professionnels", enquete_path, class: "navbar-wagon-item navbar-wagon-link" %> 
   
</div>